#!/usr/bin/env python3
"""Build image-generation prompts from an episode's approved direction.

    python scripts/build_image_prompts.py _workspace/ep01
    python scripts/build_image_prompts.py examples/sample_episode --profile comfyui

Reads `06_handoff/panel_direction.yaml` and `06_handoff/continuity_state.yaml`,
writes `07_prompts/`. Deterministic: same direction in, same prompts and seeds out.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
if hasattr(sys.stdout, "reconfigure"):  # keep output readable on legacy consoles
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from harness.config import ConfigError, load_yaml  # noqa: E402
from harness.prompts import (  # noqa: E402
    build_panel_prompt,
    build_reference_sheets,
    character_tokens,
    load_profile,
    location_token,
    style_anchor,
)

README = """# Image Prompts - {episode_id}

Generated by `scripts/build_image_prompts.py` (profile: {profile}). Do not hand-edit;
change the direction or the profile and rebuild, so prompts stay traceable to a decision.

## Order of work

1. **`refs/`** - render the character reference sheets FIRST. Everything else anchors to them.
2. Train a character LoRA on the turnaround, or wire the sheet into IP-Adapter / reference-only.
   Record the LoRA name in the profile's `character_loras`, then rebuild these prompts.
3. **`panels/`** - render panel by panel with the given size and seed.
4. Validate each panel as it lands (see `docs/IMAGE_PIPELINE.md`); re-render failures only.
5. Letter the balloons afterwards, using `lettering.md`.

## Why the art is rendered text-free

Local diffusion models do not render Korean reliably - they produce glyph-shaped noise.
So panels are generated as clean plates with balloon space reserved by the direction, and
the text is lettered on top. That also means a dialogue change costs a lettering pass
instead of a re-render.

## Files

| File | What it is |
|---|---|
| `style_anchor.txt` | Style tokens prepended to every prompt |
| `negative.txt` | Shared negative prompt |
| `characters.md` | Immutable appearance tokens per character |
| `locations.md` | `LOC_*` tokens - identical background wording across a scene |
| `refs/` | Reference sheet prompts (render these first) |
| `panels/` | One prompt file per panel |
| `lettering.md` | Balloon spec for the lettering pass |
| `manifest.json` | Machine-readable: prompts, sizes, seeds, sections |
"""


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("episode_dir", type=Path, help="episode workspace directory")
    parser.add_argument("--profile", default="comfyui", help="image-prompt profile (default: comfyui)")
    parser.add_argument("--out", type=Path, default=None, help="output dir (default: <episode>/07_prompts)")
    args = parser.parse_args(argv)

    handoff = args.episode_dir / "06_handoff"
    try:
        direction = load_yaml(handoff / "panel_direction.yaml")
        continuity = load_yaml(handoff / "continuity_state.yaml")
        profile = load_profile(args.profile)
    except ConfigError as exc:
        print(f"{exc}", file=sys.stderr)
        return 2

    tone = None
    normalized = args.episode_dir / "00_input" / "normalized_input.yaml"
    if normalized.is_file():
        tone = (load_yaml(normalized) or {}).get("tone")

    episode_id = str(direction.get("episode_id", "episode"))
    out = args.out or (args.episode_dir / "07_prompts")

    prompts = [
        build_panel_prompt(panel, episode_id=episode_id, profile=profile,
                           continuity=continuity, tone=tone)
        for panel in direction.get("panels", [])
    ]

    _write(out / "README.md", README.format(episode_id=episode_id, profile=args.profile))
    _write(out / "style_anchor.txt", style_anchor(profile, tone) + "\n")
    _write(out / "negative.txt", " ".join(str(profile.get("negative", "")).split()) + "\n")

    tokens = character_tokens(continuity)
    lines = [f"# Character Tokens - {episode_id}", "",
             "Repeat verbatim in every panel the character appears in. Marks carry their side;",
             "a mole that swaps cheeks between panels reads as a different person.", ""]
    for char_id, token in tokens.items():
        lines += [f"## {char_id}", "", "```text", token, "```", ""]
    _write(out / "characters.md", "\n".join(lines))

    location = ((continuity.get("entities") or {}).get("location")) or {}
    _write(out / "locations.md", "\n".join([
        f"# Location Tokens - {episode_id}", "",
        "Identical wording in every panel of a scene, so the background cannot drift.", "",
        f"## {location_token(location)}", "", "```text",
        str(location.get("geography", "unspecified location")), "```", "",
        f"Lighting: {(location.get('lighting') or {}).get('key', 'unspecified')}", "",
    ]))

    sheets = build_reference_sheets(continuity, profile, tone)
    ref_lines = [f"# Reference Sheets - {episode_id}", "",
                 "**Render these before any panel.** They are the consistency anchor: the LoRA",
                 "training set, the IP-Adapter reference, and what the validator compares against.",
                 "Reuse them across episodes; only new characters need a new sheet.", ""]
    for char_id, sheet in sheets.items():
        ref_lines += [f"## {char_id}", "", "### turnaround", "", "```text", sheet["turnaround"], "```", "",
                      "### expressions", "", "```text", sheet["expressions"], "```", ""]
    _write(out / "refs" / "REFERENCE_SHEETS.md", "\n".join(ref_lines))

    for prompt in prompts:
        body = [f"# {prompt.panel_id}", "",
                "## positive", "",
                "_Full prompt. Use with a runner that chunks past 77 CLIP tokens (ComfyUI)._", "",
                prompt.positive, "",
                "## positive (compact)", "",
                "_Fits in one 77-token CLIP context. Use with plain diffusers, or any runner "
                "that truncates - a truncated full prompt loses the panel's direction and keeps "
                "only the style tags._", "",
                prompt.positive_compact, "",
                "## negative", "", prompt.negative, "",
                "## generation", "",
                f"- target size : {prompt.target_width} x {prompt.target_height}",
                f"- generate at : {prompt.gen_width} x {prompt.gen_height}  (upscale x{prompt.upscale})",
                f"- seed        : {prompt.seed}",
                f"- characters  : {', '.join(prompt.characters) or 'none'}",
                f"- location    : {prompt.location_token}", ""]
        if prompt.sections:
            body += ["## sections", ""]
            body += [f"- {s.index}/{s.of} at {s.gen_width}x{s.gen_height} - {s.covers}"
                     for s in prompt.sections]
            body += [""]
        if prompt.notes:
            body += ["## notes", ""] + [f"- {n}" for n in prompt.notes] + [""]
        _write(out / "panels" / f"{prompt.panel_id}.txt", "\n".join(body))

    letter_lines = [f"# Lettering Spec - {episode_id}", "",
                    "Art is rendered text-free. Letter these on top of the finished panels.", "",
                    "| Panel | Speaker | Text | Placement |", "|---|---|---|---|"]
    for panel in direction.get("panels", []):
        for line in panel.get("dialogue") or []:
            letter_lines.append(
                f"| {panel.get('panel_id')} | {line.get('speaker', '')} | {line.get('text', '')} "
                f"| {panel.get('dialogue_space', 'unspecified')} |"
            )
    silent = [p.get("panel_id") for p in direction.get("panels", []) if not p.get("dialogue")]
    letter_lines += ["", f"Silent panels (no balloon): {', '.join(silent) or 'none'}", ""]

    prop_panels = [p for p in prompts if p.requires_lettered_prop_text]
    if prop_panels:
        letter_lines += [
            "## Prop text", "",
            "These panels need readable writing *inside the art*. The plate is rendered text-free;",
            "add the writing here, at the same resolution as the balloons.", "",
            "| Panel | What must be readable |", "|---|---|",
        ]
        for prompt in prop_panels:
            note = next((n for n in prompt.notes if "legible writing" in n), "")
            detail = note.split("(", 1)[-1].split(")", 1)[0] if "(" in note else "see panel direction"
            letter_lines.append(f"| {prompt.panel_id} | {detail} |")
        letter_lines.append("")
    _write(out / "lettering.md", "\n".join(letter_lines))

    _write(out / "manifest.json", json.dumps({
        "episode_id": episode_id,
        "profile": args.profile,
        "style_anchor": style_anchor(profile, tone),
        "negative": " ".join(str(profile.get("negative", "")).split()),
        "reference_sheets": sheets,
        "panels": [p.as_dict() for p in prompts],
    }, indent=2, ensure_ascii=False) + "\n")

    tall = sum(1 for p in prompts if p.sections)
    print(f"Wrote {len(prompts)} panel prompt(s) to {out}")
    print(f"  reference sheets : {len(sheets)}")
    print(f"  sectioned panels : {tall}")
    print("  render refs/ FIRST, then panels/, then letter from lettering.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
